server:
  port: 9999

spring:
  application:
    name: HackerrankTradingApi

  datasource:
    url: jdbc:postgresql://localhost:5432/tradings
    username: postgres
    password: root

  jpa:
     hibernate:
       ddl-auto : update
     show-sql: true




